### ISSUE TITLE
How to use and mean SecurityLevel into OAuthClient?

### ISSUE THREAD

**Issue by biapar** [mattbrailsford/umbraco-authu#10]
How to use and mean SecurityLevel into OAuthClient?

**Comment by mattbrailsford** [comment]
I'm not sure what you mean, can you explain a bit more what you are trying to achieve?

**Comment by biapar** [comment]
I wish only to say what mean SecurityLevel.

**Comment by mattbrailsford** [comment]
AuthU doesn't have a OAuthClient class so I think you may be using some other library and getting confused?

**Comment by biapar** [comment]
No. The field is into the db table OAuthClient

![image](https://user-images.githubusercontent.com/661517/27082149-e5d301a0-5043-11e7-8f1d-a6aa12277213.png)

**Comment by mattbrailsford** [comment]
Ahh, sorry, yes. This is to signify if the client is Insecure "0" such as JS, where saving your client secret would be bad, or Secure "1" if you client is compiled and so embedding the client secret is ok. If the client is "secure" then when you make a request using that client app the client secret is validated making sure requests only come from your client.

**Comment by biapar** [comment]
Ah ok. So in "secure" mode, I can call the webapi only from that clientID. Is't right?

**Comment by mattbrailsford** [comment]
that is correct yes. So say you developed a mobile app, you don't want just anyone using your api's, so this lets you restrict it to your application only. Where as for an insecure app, such as a web client, you'd probably have to secure it via the allowed origin header to only accept requests from your domain.
