### ISSUE TITLE
Error 405: The requested resource does not support http method OPTIONS

### ISSUE THREAD

**Issue by biapar** [mattbrailsford/umbraco-authu#12]
Hi,

if you call a method like your example, we receive the error "The requested resource does not support http method OPTIONS".
Why?

`[Our.Umbraco.AuthU.Web.WebApi.OAuth("realmusers")]
    public class LGIWFPraticheController : UmbracoApiController
    {

        [HttpGet]
        [Authorize]
        public string HelloWorld()
        {
            return "Hello " + Members.GetCurrentMember()?.Name;
        }

    }`

called by:
 ` var token = localStorage.getItem("token");

    var headers = new Headers();
    headers.append('authorization', 'Bearer ' + token);
 

    let options = new RequestOptions({ headers: headers });

    let body = JSON.parse('{}');

  
   return this.http.get('http://localhost:60936/umbraco/api/LGIWFPratiche/helloworld',  options)
                .map(this.handleData)
                .catch(this.handleError);`

**Comment by biapar** [comment]
Hi,
the problem is server side. How solve?

**Comment by mattbrailsford** [comment]
Sounds like you need to enable CORS, take a look here https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api#enable-cors

Ultimately, you should be able to call this in an application starting event handler:

    GlobalConfiguration.Configuration.EnableCors();

And then on your API controller, you'll need to add the endable CORS attribute:

    [EnableCors("*", "*", "*")]

You'll need to make sure the params match your configuration though. See the link for details on what those params are.

**Comment by biapar** [comment]
I follow this info by Casper 

https://our.umbraco.org/forum/extending-umbraco-and-using-the-api/76788-how-do-i-get-around-the-cross-domain-problem-using-the-umbraco-web-api-using-post#comment-245424
