### ISSUE TITLE
Where is the code to check decoration [Our.Umbraco.AuthU.Web.WebApi.OAuth("realmusers")]?

### ISSUE THREAD

**Issue by biapar** [mattbrailsford/umbraco-authu#15]
Where is the code to check decoration [Our.Umbraco.AuthU.Web.WebApi.OAuth("realmusers")]?

**Comment by mattbrailsford** [comment]
You mean this? https://github.com/mattbrailsford/umbraco-authu/blob/master/src/Our.Umbraco.AuthU/Web/Mvc/OAuthAttribute.cs
