### ISSUE TITLE
Error: on enabling of Attribute Routing

### ISSUE THREAD

**Issue by yasirbutt** [mattbrailsford/umbraco-authu#20]
I am trying to enable attribute routing for my API controller.

I used `config.MapHttpAttributeRoutes();` in my webapiconfig registration method then i got error 

> And endpoint for the realm "default" has not yet been configured. Please call ConfigureEndpoint first.

can you please help me to enable Attribute routing?

/yasir

**Comment by mattbrailsford** [comment]
I'm going to need more information. What does your AuthU config look like?

**Comment by mattbrailsford** [comment]
Closing the issue due to insuficient information. Feel free to reopen with more details but as it stands I can't replicate.
