### ISSUE TITLE
Dependency issue with System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by giuunit** [mattbrailsford/umbraco-authu#21]
Hi, 
In the list of dependencies, there seem to be breaking changes between System.IdentityModel.Tokens.Jwt 4.0.40306.1554 & 5.

It might be interesting to add an extra dependency in NuGet for the project:
System.IdentityModel.Tokens.Jwt (<= 4.0.40306.1554) to stop NuGet from installing incompatible version of this dll.

Apologies for the format, I am not very familiar with push requests nor NuGet dependency config files.

**Comment by mattbrailsford** [comment]
Good suggestion. There is already an issue regarding upgrading JWT over on issue #19 so I'll close this issue down and deal with all JWT via that issue.
