### ISSUE TITLE
What is the use for 'ProtectedTicket'

### ISSUE THREAD

**Issue by cfr-op10** [mattbrailsford/umbraco-authu#22]
Hi,

I am just curious: What's the use for the `ProtectedTicket` property in the `OAuthRefreshToken` class?

https://github.com/mattbrailsford/umbraco-authu/blob/master/src/Our.Umbraco.AuthU/Models/OAuthRefreshToken.cs

It's nowhere used, just stored into the database...

Thanks
Calvin

**Comment by mattbrailsford** [comment]
Haha, good question. I based this on some other works which was actually meant to use this as part of the refresh token re-authentication workflow, as it should contains all the claims etc of the authenticated user, but it actually looks like I just re-authenticate the user based on the stored username. We could probably get rid of it :)

**Comment by cfr-op10** [comment]
Would it make sense (in your opinion) to use the stored (encrypted) claims from the database or always re-authenticated based on the username? Probably performance-wise it's better to re-use it from the database but security-wise... probably not?

**Comment by mattbrailsford** [comment]
I'm not actually sure how much performance you'd save as you'd still need to hit the DB to compare the refresh token and to create and store a new one so all it saves is the auth lookup bit and I think I'd rather have the extra security that the claims are re-checked on every refresh, just in case any permissions were revoked / added.

**Comment by cfr-op10** [comment]
Nice, thanks for the fast reply! I have the same opinion as you.
