### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#24]
Are all these dependencies really necessary? https://github.com/mattbrailsford/umbraco-authu/blob/501c66cc492685bc7ca018b7149caec0d3b1b34c/src/Our.Umbraco.AuthU/packages.config
![image](https://user-images.githubusercontent.com/2511610/44147645-32c00ab0-a095-11e8-8c7c-f3f4fc5f508a.png)
SharpZipLib, Owin and Microsoft.AspNet.Razor is for example never used what I can see, and couldnt they screw with Umbracocms.core's dependencies?

**Comment by mattbrailsford** [comment]
Those are the umbraco dependencies. AuthU just has a dependency on UmbracCms.Core, which in turn has all those dependencies.

**Comment by tobbbe** [comment]
awwwwww so sorry!! yes, just realized when i posted the issue 🤦‍♂️ 🤦‍♀️

**Comment by mattbrailsford** [comment]
No problem :)
