### ISSUE TITLE
ClockSkew makes token not expire

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#25]
As per https://stackoverflow.com/questions/39728519/jwtsecuritytoken-doesnt-expire-when-it-should.

If you have short access_token lifetime (2min ex) they wont expire until 5min.

Setting ClockSkew to 0 TimeSpan.Zero fixes this:
```
var tokenValidationParameters = new TokenValidationParameters
{
    //...your setting

    // set ClockSkew is zero
    ClockSkew = TimeSpan.Zero
};
```

An alternative would be to allow to configure all TokenValidationParameters in setup? I could make a PR for that :)

**Comment by mattbrailsford** [comment]
Fixed in commit ce1632b
