### ISSUE TITLE
Stay logged in on multiple devices

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#29]
If I login on Device1 and then on Device2 and then refresh the token on Device2 [this line](https://github.com/mattbrailsford/umbraco-authu/blob/e59d31f34e81f9c3e032ecf254a0050849ea9ee7/src/Our.Umbraco.AuthU/Data/UmbracoDbOAuthRefreshTokenStore.cs#L20) will cause Device1's refresh_token to be invalid. Would it be possible to add a column that stores ex deviceId? To be able to keep multiple devices logged in

**Comment by mattbrailsford** [comment]
Closing this issue as I've started a pull request for this feature so we can continue the conversation on PR #30
