### ISSUE TITLE
how to change the response payload 

### ISSUE THREAD

**Issue by ghost** [mattbrailsford/umbraco-authu#31]
from 
`{
    "invalid_grant": "The username and/or password is incorrect"
}`

to 
`{
"success":"error",
    "message": "The username and/or password is incorrect"
}`

**Comment by mattbrailsford** [comment]
@abedbilani this is not currently configurable. If you needed different error messages, you'd have to compile a custom build. We use the best practise of communicating the error state with response codes therfore the body of the response is just a helpful message.
