### ISSUE TITLE
Members and Realms

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#33]
If I have a Endpoint Configured like this `OAuth.ConfigureEndpoint("portal", "oauth/portal/token",authuOptions);`, how am I suppose to make sure only members who has access to that realm can login with that endpoint? Any member can login to it right?

**Comment by mattbrailsford** [comment]
To control permissions on an endpoint you would use the standard `AuthorizeAttribute` which allows you to set required roles you need to access them. 

Realms are really for just segregating your endpoints.

**Comment by tobbbe** [comment]
aaah okey, so something like `[MemberAuthorize(AllowType = "Retailers")]`?

**Comment by mattbrailsford** [comment]
I think you can use the default AuthorizeAttribute rather than the MemberAuthorizeAttribute (though could be wrong) but yea, that's the idea. 👍

**Comment by tobbbe** [comment]
hmm, I have two apis: app and portal. Some users should be able to access portal, but not all. This means that all users will be able to login to portal (through the `oauth/portal/token` endpoint), since it not protected by roles or anything else.

The only way to protect the portal API is to use something like [MemberAuthorize(AllowType = "Retailers")] on all controllers. But everyone can still login.

There's no way to avoid this right? Doesnt that make realms a bit useless, since there is no way to ensure only some users can access the realm-login-endpoint?

**Comment by tobbbe** [comment]
hmm, just read your first response again. So understand now that realms has nothing to do with authorization. But it would be nice heheh!

**Comment by mattbrailsford** [comment]
Yea, I'm pondering.

There is a distinct difference between Authentication and Authorization. The token endpoints only provide authentication (you are who you say you are) but it's up to your controllers to apply the authorization (you can only do what you are allowed to do) so for the endpoint to restrict people means it's also performing some kind of authorization too. 

That said, I guess it does seem weird that people can authenticate against either endpoint. 🤔

**Comment by mattbrailsford** [comment]
As a workaround what you could do is implement 2 `OAuthUserService`'s that inherit from the `UmbracoMembersOAuthUserService` and have each one perform the member restrictions as part of the `ValidateUser` methods then for each of your endpoint configurations, point each one to their own implementation.

You could probably in fact just implement 1 and pass in a list of allowed roles / members types into the constructor.

    OAuth.ConfigureEndpoint("realm1", "/endpoint1/oauth/token", new OAuthOptions {
        UserService = new MyUmbracoMembersOAuthUserService(new [] { "Role1", "Role2" }),
        SymmetricKey = "856FECBA3B06519C8DDDBC80BB080553",
        AccessTokenLifeTime = 20, // Minutes
        AllowInsecureHttp = true // During development only
    });

    OAuth.ConfigureEndpoint("realm2", "/endpoint2/token", new OAuthOptions {
        UserService = new MyUmbracoMembersOAuthUserService(new [] { "Role3", "Role4" }),
        SymmetricKey = "856FECBA3B06519C8DDDBC80BB080553",
        AccessTokenLifeTime = 20, // Minutes
        AllowInsecureHttp = true // During development only
    });

**Comment by tobbbe** [comment]
SUPER! Ill try that! thank you so much once again 😃

**Comment by tobbbe** [comment]
Since `ValidateUser(username)` and `ValidateUser(username)` [isnt abstract or virtual](https://github.com/mattbrailsford/umbraco-authu/blob/b21f52d4ef5f978e6181d38854271da1aa47cc4f/src/Our.Umbraco.AuthU/Services/MembershipProviderOAuthUserService.cs#L22) I cant override them. So I copied everything from `MembershipProviderOAuthUserService` instead. Would it be possible to make them virtual? Also does this look okey?

```
public class SpecialUmbracoMembersOAuthUserService : IOAuthUserService
{
        
    public string[] AllowedRealms { get; set; }

    public string UserType => "UmbracoMember";

    public string MembershipProviderName => "UmbracoMembershipProvider";

    protected MembershipProvider MemberProvider => Membership.Providers[this.MembershipProviderName];

    public bool ValidateUser(string username)
    {
        var user = this.MemberProvider.GetUser(username, false);
        return user != null && **ValidateRealms(username)** && user.IsApproved && !user.IsLockedOut;
    }

    public bool ValidateUser(string username, string password)
    {
        return **ValidateRealms(username)** && this.MemberProvider.ValidateUser(username, password);
    }

    public IEnumerable<Claim> GetUserClaims(string username)
    {
        var member = this.MemberProvider.GetUser(username, true);
        if (member != null)
        {
            yield return new Claim(ClaimTypes.NameIdentifier, member.ProviderUserKey.ToString());

            var roles = Roles.GetRolesForUser(member.UserName);
            foreach (var role in roles)
            {
                yield return new Claim(ClaimTypes.Role, role);
            }
        }
    }

    public bool ValidateRealms(string username)
    {
        if (AllowedRealms == null)
        {
            return true;
        }

        var member = this.MemberProvider.GetUser(username, false);

        if (member != null)
        {
            var roles = Roles.GetRolesForUser(member.UserName);
            return roles.ContainsAny(AllowedRealms);
        }

        return false;
    }
}
```

**Comment by tobbbe** [comment]
You probably would want to do some kind of [check here](https://github.com/mattbrailsford/umbraco-authu/blob/e59d31f34e81f9c3e032ecf254a0050849ea9ee7/src/Our.Umbraco.AuthU/Web/Controllers/OAuthController.cs#L130) to if the user still belongs to the realm (1. user belongs to realm, logs in, 2. user gets removed from realm, 3. user needs to refresh token, 4. right now only the claim is checked againts the realm)

(just ignore me if im talking to much in your repos 😬 )

**Comment by mattbrailsford** [comment]
@tobbbe all good stuff. If you can raise them as individual issues though that would be great so that they can all be addressed and tracked.

Thanks for trying things out and reporting back.

**Comment by mattbrailsford** [comment]
Hmm, RE your last comment about `ProcessUsernameRequest` (which is now `GenerateTokenResponse`), this method is only every called after an authentication request has been made and realms etc checked so that shouldn't be necessary.
