### ISSUE TITLE
Realms not working

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#34]
Realms seems not to be working as expected (for both 1.0.2 and 1.0.3). Having below will cause this error  when calling `/oauth/portal/token` and login into umbraco backend does not work (cors-error)

`And endpoint for the realm "default" has not yet been configured. Please call ConfigureEndpoint first`  

```
namespace Test.ApiControllers
{
    [EnableCors("*", "*", "*")]
    [OAuth(Realm = "portal")]
    [JsonCamelCaseFormatter]
    public class PortalBaseSecureController : UmbracoApiController
    {
    }
}
```

```
namespace Test
{
    class UmbracoSetup : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase app, ApplicationContext ctx)
        {
            GlobalConfiguration.Configuration.EnableCors();

            var authuOptions = new OAuthOptions
            {
                UserService = new UmbracoMembersOAuthUserService(),
                SymmetricKey = Settings.Default.AuthuSymmetricKey,
                AccessTokenLifeTime = 2,
                AllowInsecureHttp = true,
                RefreshTokenStore = new UmbracoDbOAuthRefreshTokenStore(),
                AllowedOrigin = "*"
            };

            // uncomment this to be able to login to umbraco backend
            // OAuth.ConfigureEndpoint(new OAuthOptions());

            OAuth.ConfigureEndpoint("portal", "oauth/portal/token",authuOptions);
        }
    }
}
```

Uncommenting the `OAuth.ConfigureEndpoint(new OAuthOptions());` line above makes login into umbraco and the `oauth/portal/login` endpoint to work.

But! having below apicontroller causes 401 :(

```
namespace Test.ApiControllers
{
    [EnableCors("*", "*", "*")]
    [OAuth(Realm = "portal")]
    [JsonCamelCaseFormatter]
    public class PortalBaseSecureController : UmbracoApiController
    {
        [HttpGet]
        [Authorize]
        public IHttpActionResult Orders()
        {
            return Ok("");
        }
    }
}
```

Setting AllowedOrigin to null didnt help

**Comment by mattbrailsford** [comment]
Ahhh, I bet you are using the `OAuthAttribute` from the wrong namespace.

There are 2 `OAuthAttributes`, one for API controllers, and one for standard controllers (this is true in other OAuth implementations), unfortunately they have different implementations so we have to have seperate attributes. 

Make sure you are using the one in the `OAuth.Web.WebApi` namespace (annoying I know, but unforunately unavoidable)

**Comment by tobbbe** [comment]
Unfortunately I think I use the right one :/

```
using Our.Umbraco.AuthU.Web.WebApi;
using System.Web.Http.Cors;
using Umbraco.Web.WebApi;

namespace Test.ApiControllers
{
    [EnableCors("*", "*", "*")]
    [OAuth(Realm = "portal")]
    [JsonCamelCaseFormatter]
    public class PortalBaseSecureController : UmbracoApiController
    {
    }
}
```

**Comment by mattbrailsford** [comment]
But that doesn't have a realm defined?

**Comment by tobbbe** [comment]
oh sorry! I've removed all realm-stuff for now. But I tested with it!

Edited comment

**Comment by mattbrailsford** [comment]
And you tried it with the other namespace? (I can never remember which is which)

**Comment by tobbbe** [comment]
Not tried, but the other one is `Our.Umbraco.AuthU.Web.Mvc;` and that makes no sence in a web api? Or do you mean an attribute thats not in `Our.Umbraco.AuthU`?

**Comment by mattbrailsford** [comment]
I mean the one in Our.Umbraco.AuthU.Web.Mvc. Doesn't hurt to try to rule it out.

**Comment by tobbbe** [comment]
okey! made a try, same thing im afraid

**Comment by mattbrailsford** [comment]
Then I'm a bit stumpped at the moment. You might have to pull the source and debug in. Not sure why Realm wouldn't be coming through.

**Comment by tobbbe** [comment]
This is interesting! If I set the realm to "default": `[OAuth(Realm = "default")]` and `OAuth.ConfigureEndpoint("default", "/oauth/portal/token", authuOptions);` it works! Even the bug with not beeing able to login to umbraco backend is gone.

So somewhere the realm is not coming though. I've checked the JWT and the realm claim is there, so it must be in the validation somewhere. Ill try to debug

**Comment by tobbbe** [comment]
Im unable to compile the project so I cant debug. Ive forked the project and tried both master and develop branches. What have I done wrong?

![image](https://user-images.githubusercontent.com/2511610/52436290-3af53700-2b14-11e9-8505-0ee1129260bf.png)

edit: haha umbraco changed the name... https://github.com/umbraco/Umbraco-CMS/commit/2c3a2b29b2bdaa2db5c65da215ae6e44ccf9196c#diff-8aba4e505340b4949bce3c75076b8fed

**Comment by tobbbe** [comment]
omg. I found it! I used `[OAuth(Realm = "portal")]` but should have used `[OAuth("portal")]` 🤦‍♂️ 

Changing `public string Realm { get; set; }` to private would prevent others from doing the same misstake. Dont know if that would have any other impact though?

Ive learned alot from your code today! 😃

**Comment by mattbrailsford** [comment]
Reopening issue to make sure this gets resolved as we should either prevent that usage, or make that style possible.

**Comment by mattbrailsford** [comment]
I've pushed an update in commit f347191 that should now allow you to do `[OAuth(Realm = "myrealm")]`. Would be great if you could give it a try.

You can find a nightly build on the build server https://ci.appveyor.com/project/mattbrailsford/umbraco-authu/build/artifacts

**Comment by tobbbe** [comment]
tested, worked like a charm!

**Comment by mattbrailsford** [comment]
Awesome. Thank you
