### ISSUE TITLE
umbraco cloud/IIS not working

### ISSUE THREAD

**Issue by baatten** [mattbrailsford/umbraco-authu#37]
Hi.

i really need some help. i feel like i tried everything, so trying to write here.

i can't get token post to work. the api works if i don't put authorize attribute on it, and if i do put it on a method i get the correct unautroized response. all great.

but i cannot call the oath/token i always get the {"Message":"The requested resource does not support http method 'GET'."} response.

i am using x-www-form-urlencode. with password and username/password.

if i run it on local machine all work ok. if i upload to umbraco cloud or other IIS it does not work.

anyone have any idea?

Thanks a lot

**Comment by mattbrailsford** [comment]
What code are you using to make your token request?

**Comment by baatten** [comment]
Right now as basic as possible, so just postman.

**Comment by mattbrailsford** [comment]
Can you share a screenshot? Hard to say what the problem is without knowing exactly what you are trying.

**Comment by baatten** [comment]
![Image 4-15-19 at 21 55](https://user-images.githubusercontent.com/22172136/56157875-43149b80-5fc9-11e9-8513-2971c126ece7.jpg)

**Comment by mattbrailsford** [comment]
Do you happen to have some redirects setup on your live site? My guess is you are posting but then you are being redirected which then makes it a get request.

**Comment by baatten** [comment]
there is some redirects inside Umbraco inside url management. is that what you think about?

**Comment by baatten** [comment]
All the methods work, just OAuth/token has this behavior.

**Comment by mattbrailsford** [comment]
I meant more in your web.config. Something like a HTTPS redirect (I can't see what protocol you are using so not sure if you are using HTTP or HTTPS). Umbraco cloud might do that by default so if you are requesting HTTP try HTTPS instead. 

Ultimately something is converting your post to a get request and the only thing I know that does this is a rogue rewrite somewhere.

**Comment by baatten** [comment]
You were right Matt, there is a rewrite by default on my site. non www requests are directed to www address.

so to anyone else, this can be solved by checking rewrites.

Matt, thanks a lot, took me 12 hour to write to you. appreciate the insight, and the package :-)

**Comment by mattbrailsford** [comment]
No problem. Glad you got it working. 👍
