### ISSUE TITLE
NullReferenceException when using UmbracoUsersOAuthUserService

### ISSUE THREAD

**Issue by ghost** [mattbrailsford/umbraco-authu#39]
When using the UmbracoUsersOAuthUserService and validating an invalid username, the controller responds with a 500 - Internal Server Error:

```
{
"message": "An error has occurred.",
"exceptionMessage": "Object reference not set to an instance of an object.",
"exceptionType": "System.NullReferenceException",
"stackTrace": " at Umbraco.Web.Security.Providers.UsersMembershipProvider.PerformValidateUser(String username, String password) at Umbraco.Web.Security.Providers.UmbracoMembershipProvider`2.ValidateUser(String username, String password) at Our.Umbraco.AuthU.Web.Controllers.OAuthController.ProcessPasswordTokenRequest(OAuthTokenRequest request) in C:\projects\umbraco-authu\src\Our.Umbraco.AuthU\Web\Controllers\OAuthController.cs:line 113 at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
```

We're using Umbraco 7.12.4 and AuthU 1.0.3. Does this ring a bell for anyone?

And secondly, when using the UmbracoUsersOAuthUserService, in a controller decorated with OAuth attribute, how to get the current user?

**Comment by mattbrailsford** [comment]
@highstone when you say "invalid username" in what sense is it invalid? Empty? Null? Doesn't exist in the database?

Looking at the error, it appears this is coming from the Umbraco MembershipProvider rather than AuthU. We might be able to work around it, but really that behaviour should be raised on the Umbraco repo.

The UmbracoUserOAuthUserService is just used by the OAuth logic to know what to validate against. Once you've validated a user and you are accessing a controller, you access the current user as you would a regular umbraco controller at that point. I believe it's on the Securty service.

**Comment by ghost** [comment]
Hey @mattbrailsford, it appears to be null, according to the exception thrown ;-) 
The thing is that when you're trying to validate a non-existing user (or invalid username for that matter) the exception is thrown. I believe too it's more Umbraco related than the implementation of the IUserService. I tried tracking it down a couple of weeks ago, but we eventually decided to go another route and add the authorised API users as Umbraco Members instead of Umbraco Users, as this also solved another issue (customer related).

But as this impacts the use of the UmbracoUsersOAuthUserService I wanted to notify you on this because it makes the UmbracoUsersOAuthService pretty much useless. You should be able to reproduce this very easy. It only happens for non-existing users that you try to validate.

**Comment by mattbrailsford** [comment]
Ok, I've added try / catch statements around all calls to membership providers methods so if it does error, it just returns false

**Comment by ghost** [comment]
Excellent, that should solve the issue for anyone running into this.
