### ISSUE TITLE
Access-Control-Allow-Origin can be added twice, is blindly added OAuthController

### ISSUE THREAD

**Issue by Steffeng87** [mattbrailsford/umbraco-authu#4]
It would be nice to be able to turn off the Access-Control-Allow-Origin header from the OAuthController, as this will often be set globally for the application, assuming a scenario where the Auth server is also the resource server (which will probably be the case since this is made for umbraco)

Specifically this line is giving us problems:
`HttpContext.Current.Response.Headers.Add("Access-Control-Allow-Origin", Client != null ? Client.AllowedOrigin : Context.Options.AllowedOrigin);`

**Comment by mattbrailsford** [comment]
Closing as fixed by merged in PR #5
