### ISSUE TITLE
how to OAuth.ConfigureEndpoint advance?

### ISSUE THREAD

**Issue by hakan-lekesiz** [mattbrailsford/umbraco-authu#42]
I want to use OAuth.ConfigureEndpoint advance. where and how should I add this configuration in project? is it globa.asax? please give more information in documantation.

**Comment by mattbrailsford** [comment]
As per the documentation here https://github.com/mattbrailsford/umbraco-authu#configuration it is configured within an umbraco `ApplicationEventHandler`. The documentation provides you with a basic stub of one of these, and then also gives you examples of the different configurations. Those will replace line 5 of the `ApplicationEventHandler` stub.
