### ISSUE TITLE
Do Work it with Umbraco 8?

### ISSUE THREAD

**Issue by biapar** [mattbrailsford/umbraco-authu#45]
Do Work it with Umbraco 8?

**Comment by cdecinkoKnight** [comment]
Also need to know if this works with Umbraco 8.x.

**Comment by tobbbe** [comment]
Nope, does not work with Umbraco 8.x

**Comment by mattbrailsford** [comment]
There is a PR for v8 here https://github.com/mattbrailsford/umbraco-authu/pull/38 Unfortunately I'm struggling to find the time to get it merged in, but you are welcome to test it and provide any feedback on the PR.

**Comment by biapar** [comment]
I see the new version. Very good. Can I try it?

**Comment by somoreingold** [comment]
Similarly, is version 2.0 compatible with Umbraco 7.x? Thanks!

**Comment by mattbrailsford** [comment]
@biapar yup, v2 is Umbraco v8 compatible so feel free to try it

@somoreingold no, v2 is Umbraco v8+ only

**Comment by somoreingold** [comment]
@mattbrailsford thank you, that is good to know. For now I'll need to try this on Umbraco 7 (so I suppose that's v1.0.3). Would any future critical bugs with v1.x be addressed, or will all focus be on v2+?
