### ISSUE TITLE
Commits missing from nuget version 1.0.3

### ISSUE THREAD

**Issue by tobbbe** [mattbrailsford/umbraco-authu#49]
I noticed that I cant override `ValidateUser` from `MembershipProviderOAuthUserService` when using nuget version 1.0.3, even though github "Release page" says it should be in the 1.0.3 tag in this commit: https://github.com/mattbrailsford/umbraco-authu/commit/dd746b8d365b67716f70a00fece737a59f08b2af

So I checked the nuget content and this change among a couple of others commits are missing in the files 😱 

Maybe the wrong tag was selected for the build service? Could you release a fixed 1.0.4? 😄

**Comment by biapar** [comment]
I know that there is no a 1.0.4 but jump to 2.0
In the 1.0.3 on my pc I've:
 public bool ValidateUser(string username)
        {
            var user = this.MemberProvider.GetUser(username, false);
            return user != null && user.IsApproved && !user.IsLockedOut;
        }

        public bool ValidateUser(string username, string password)
        {
            return this.MemberProvider.ValidateUser(username, password);
        }

**Comment by tobbbe** [comment]
Unfortunately I cant use 2.0 since I'm on umbraco 7 :/

**Comment by biapar** [comment]
> Unfortunately I cant use 2.0 since I'm on umbraco 7 :/

See the code in my comment.

**Comment by biapar** [comment]
Yes but you can use 1.0.3 as me that I'm on 7.
If you want I can pass you the dll.
