### ISSUE TITLE
Error upgrading to umbraco version 7.6

### ISSUE THREAD

**Issue by TimPickin** [mattbrailsford/umbraco-authu#6]
When I upgraded my umbraco nuget package to 7.6, the backend asks you to log in to authorise the upgrade, when I tried to log in, I got an error thrown from this line OAuth.cs - throw new Exception($"And endpoint for the realm \"{realm}\" has not yet been configured. Please call ConfigureEndpoint first.");

I had to comment this line out and just return config from the GetContext method for the upgrade process to work, after this I could reset this file to before and it worked fine.

**Comment by mattbrailsford** [comment]
Closing this issue, we can continue the discussion in the PR #7
